# Generated by Django 5.0.3 on 2024-04-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tizhoshan',
            name='status',
            field=models.CharField(choices=[('First high school', 'متوسطه اول'), ('second high school', 'متوسطه دوم')], default='First high school', max_length=60, verbose_name='وضعیت'),
        ),
    ]
