# Generated by Django 5.0.3 on 2024-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tizhoshan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tizhoshan',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='ویدیو خود را وارد کنید'),
        ),
    ]
