# Generated by Django 5.0.3 on 2024-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_tizhoshan_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tizhoshan',
            name='video',
            field=models.FileField(default=None, upload_to='', verbose_name='ویدیو خود را وارد کنید'),
        ),
    ]
