# Generated by Django 5.0.3 on 2024-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_tizhoshan_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konkor_sarasari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('experimental', 'تجربی'), ('Math', 'ریاضی'), ('Humanities', 'انسانی'), ('art field', 'هنر')], default='تجربی', max_length=60, verbose_name='مشخصات گروه')),
                ('image', models.ImageField(blank=True, default=None, upload_to='', verbose_name='تصویر')),
                ('news', models.TextField(verbose_name='اخبار')),
                ('video', models.FileField(blank=True, default=None, upload_to='', verbose_name='ویدیو خود را وارد کنید')),
            ],
        ),
        migrations.AlterField(
            model_name='tizhoshan',
            name='status',
            field=models.CharField(choices=[('First high school', 'متوسطه اول'), ('second high school', 'متوسطه دوم')], default='First high school', max_length=60, verbose_name='مشخصات گروه'),
        ),
    ]
