# Generated by Django 5.0.3 on 2024-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_azmon_class_jozve_konkor_arshad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moshavere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ministry of Science 1', 'زیر گروه یک وزارت بهداشت'), ('Ministry of Science 2', 'زیر گروه دو وزارت بهداشت'), ('Ministry of Science 3', 'زیر گروه سه وزارت بهداشت'), ('Ministry of Science 3', '(رشته های شناور) وزارت بهداشت'), ('Ministry of Health 1', 'وزارت علوم'), ('experimental', 'تجربی'), ('Math', 'ریاضی'), ('Humanities', 'انسانی'), ('art field', 'هنر'), ('First high school', 'متوسطه اول'), ('second high school', 'متوسطه دوم')], default='تجربی', max_length=60, verbose_name='مشخصات گروه')),
                ('slug', models.SlugField(max_length=100, verbose_name='لینک')),
            ],
        ),
        migrations.CreateModel(
            name='Nafarat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ministry of Science 1', 'زیر گروه یک وزارت بهداشت'), ('Ministry of Science 2', 'زیر گروه دو وزارت بهداشت'), ('Ministry of Science 3', 'زیر گروه سه وزارت بهداشت'), ('Ministry of Science 3', '(رشته های شناور) وزارت بهداشت'), ('Ministry of Health 1', 'وزارت علوم'), ('experimental', 'تجربی'), ('Math', 'ریاضی'), ('Humanities', 'انسانی'), ('art field', 'هنر'), ('First high school', 'متوسطه اول'), ('second high school', 'متوسطه دوم')], default='تجربی', max_length=60, verbose_name='مشخصات گروه')),
                ('summery', models.CharField(max_length=150, verbose_name='نام نفرات برتر')),
            ],
        ),
    ]
