# Generated by Django 5.0.3 on 2024-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_konkor_doctora_alter_azmon_status_alter_class_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
